name: ci-test

on:
        push:
                branches: ["master"]
        pull_request:
                branches: ["master"]

jobs:
        test:
                runs-on: ubuntu-latest
                services:
                        postgres:
                                image: postgres:12
                                env:
                                        POSTGRES_USER: postgres
                                        POSTGRES_PASSWORD: baped
                                        POSTGRES_DB: go_db
                                options: >-
                                        --health-cmd pg_isready
                                        --health-interval 10s
                                        --health-timeout 5s
                                        --health-retries 5
                steps:
                        - uses: actions/checkout@v3

                        - name: Install Migration CLI
                          run: |
                                  mkdir migrate_temp
                                  curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-amd64.tar.gz | tar xvz -C migrate.linux-amd64
                                  sudo migrate.linux-amd64 /usr/bin/
                                  which migrate

                        - name: Run migration
                          run: make migrateup

                        - name: Set up Go
                          uses: actions/setup-go@v4
                          with:
                                  go-version: "1.21.4"

                        - name: Test
                          run: make test
